### ISSUE TITLE
Rotation incorrectly reprojects image

### ISSUE THREAD

**Issue by Chris-Schnaufer** [OpenDroneMap/FIELDimageR#11]
[Rotating the image](https://github.com/OpenDroneMap/FIELDimageR#3-rotating-the-image) in the instructions causes the image to [reproject](https://github.com/OpenDroneMap/FIELDimageR/blob/603a31fab2facd19b1f3fa4aa393a59ea164fb10/R/fieldRotate.R#L19). This causes the rotated image to have incorrect geographic coordinates. The pixels need to be rotated and the geographic information to remain intact.

A way to think about this is recognizing that the original image covers a certain area of the ground; represented by the geographic coordinate system and the image geographic extents. When the rotation step is performed, the image still represents the **exact same** geographic coordinate system and extents as the original image, only the pixel representation is different.

The following, unassociated, link shows the effect of the reprojection geographically: https://gis.stackexchange.com/questions/131465/gdal-rotate-dem (first response, under Update). As can be seen, the image is now covering a different geographic area after rotation.

The two images in the _Rotating the image_ section display the same area of ground, only the pixel representation has changed.

_What worked for me_
I couldn't find an easy way to rotate the pixels in `R`, not a strong language for me. What I was able to do is assign the Crop crs and extent back to the rotated image as follows: 
```r
crs(EX1.Rotated)<-crs(EX1.Crop)
extent(EX1.Rotated)<-extent(EX1.Crop)
```
Having a background in GIS, I need to point out that this is an inexact solution that may be considered "close enough".

**Comment by filipematias23** [comment]
Hi @Chris-Schnaufer,

I have been thinking on a way to fix this rotation problem. I have some ideas, as soon as I get more improvment on that I will get back to you. Thank you for your suggestion..!!!

Let me know if you have any other idea.

All the best,
Filipe

**Comment by filipematias23** [comment]
Hi @Chris-Schnaufer ,

I just uploaded the new version of FIELDimageR (**0.2.8**). In this version, I fixed the rotation issue. Now, it's possible to fit the shapefile back to the original image using the same CRS. 

For more information: 
(1) [https://github.com/OpenDroneMap/FIELDimageR#P3](https://github.com/OpenDroneMap/FIELDimageR#P3) 
(2) [https://github.com/OpenDroneMap/FIELDimageR#P5](https://github.com/OpenDroneMap/FIELDimageR#P5)

Thank you for your suggestions...!

All the best,
Filipe
