### ISSUE TITLE
fieldIndex() function is not available

### ISSUE THREAD

**Issue by tejshahi** [OpenDroneMap/FIELDimageR#12]

**Comment by tejshahi** [comment]
fieldIndex() function is not available error! do anyone feel it?

**Comment by filipematias23** [comment]
Hey there, which version of FIELDimageR are you using?
fieldIndex() was called indices() in older versions.
Could you please try to upload the new version and try run the code again?
All the best,
Filipe

**Comment by tejshahi** [comment]
Thanks! mine was old version! now I updated.
Many Thanks
Tej
