### ISSUE TITLE
EX1.Shape$fieldShapeGIS does not have a CRS

### ISSUE THREAD

**Issue by Chris-Schnaufer** [OpenDroneMap/FIELDimageR#16]
When following the examples in the README, I found I was not able to transform `EX1.Shape$fieldShapeGIS` to a Lat-Long coordinate system due to a lack of CRS. I found a CRS on `EX1.Shape$fieldShape` and was able to assign that, perform the translation, and export the GeoJSON of `EX1.Shape$fieldShapeGIS`

It would be nice to have the CRS automatically assigned to EX1.Shape$fieldShapeGIS

**Comment by filipematias23** [comment]
Hi @Chris-Schnaufer,

I just fixed the CRS for EX1.Shape$fieldShapeGIS... Thank you.

Could you please download the package again and let me know if it is working well on your computer?

Thank you,
Filipe

**Comment by Chris-Schnaufer** [comment]
Hello @filipematias23. This change looks good. Thanks for the quick turn around!

**Comment by filipematias23** [comment]
Actually, thank you for helping to improve FIELDimageR.

Let me know if you have any other suggestions.

All the best,
Filipe
