### ISSUE TITLE
Dockerfile missing

### ISSUE THREAD

**Issue by weiyaw** [OpenDroneMap/FIELDimageR#23]
Hi,

Is there any chance the Dockerfile will be added back?

I have a copy of Dockerfile based on rocker/tidyverse:4.1.0 and am happy to share it.

Regards,

Kenyon

**Comment by filipematias23** [comment]
Hi Kenyon,

Thank you for contacting us and for sharing. We just merged your pull request. Could you check if it is working for you?

All the best,
Filipe

**Comment by weiyaw** [comment]
Yes it's working. Thanks.
