### ISSUE TITLE
Parallel and loop to evaluate multiple images

### ISSUE THREAD

**Issue by volpatoo** [OpenDroneMap/FIELDimageR#30]
Hi all,
I am using the object n.core from the function "fieldInfo" and when I set up the number of cores, this function does not work
Do you have any thoughts on what it can be? 

Thanks

Leonardo Volpato

**Comment by filipematias23** [comment]
Hi Leonardo,

Which FIELDimageR version are you using?

Once we made a change in the code that caused this problem during the parallel. We fixed it in the last version. 

I recommend using the last version.

Please, let us know if it worked.

All the best,
Filipe

**Comment by volpatoo** [comment]
Hi Dr. Fillipe and team.
Thanks for your prompt response about it. I forgot to reply to you before, but updating the FIELDimageR package solved this problem. Also, I needed admin permission to run it, which I already figured out it too. 

Many thanks,
Leonardo
