### ISSUE TITLE
 plotRGB: cannot allocate vector of size 4.9 Gb

### ISSUE THREAD

**Issue by lucassantoscorrea** [OpenDroneMap/FIELDimageR#5]
IS THERE ANY LIMITATION ON THE SIZE OF IMAGES TO BE PROCESSED IN YOUR SOLUTION?

BRAZILIAN HERE, LITTLE KNOWLEDGE OF ENGLISH!

**Comment by filipematias23** [comment]
Ola Lucas,
Obrigado por perguntar. 
O R inicialmente não e um software de analise de imagens ou documentos pesados, então um arquivo de 5Gb provavelmente não vai abrir facilmente na area de plotagem. Eu recomendo algumas estratégias: i) reduzir o tamanho da imagem com a função aggregate; ii) cortar a imagem em tamanhos menores e trabalhar com um pedaço por vez; iii) aumentar a memória de uso do R; iv) remover objetos não usados no pipeline (voce pode sobrescreve-los salvando com o mesmo nome); v) em ultimo usar outro software como o QGIS. Eu escrevi um pouco sobre isso nesse link: [https://github.com/OpenDroneMap/FIELDimageR#P20](https://github.com/OpenDroneMap/FIELDimageR#P20) . Deixe-me saber se tem mais duvidas.

Tudo de bom,
Filipe Matias

**Comment by lucassantoscorrea** [comment]
Obrigado chefia!
