### ISSUE TITLE
fieldArea

### ISSUE THREAD

**Issue by AparicioJohan** [OpenDroneMap/FIELDimageR#58]
Hi dear Filipe, 
Happy new year!

I was trying to use the function fieldArea and noticed that the ID order of the objects don't match so the cbind does not work here. What I did was to include this (`fieldShape <- arrange(fieldShape, ID)`) in the function to fix it, but it guess you have a better way to do it.

![imagen](https://github.com/OpenDroneMap/FIELDimageR/assets/44405276/e98128cf-d94b-47c4-9c1a-9080d174becf)

Thank you for developing this amazing package!
Johan

**Comment by filipematias23** [comment]
Hi Johan,

Thanks for contacting us and for your feedback!

Dr Popat has been changing many functions and meking them better and better...!

I guess you can fix this issue by using field=PlotID ... The default was 'ID', we just upload the package to use PlotID instead ID.

Couls you please upload your version and check if it is working better now?

[Check fieldArea changes!](https://github.com/OpenDroneMap/FIELDimageR/commit/40901bf52676c4288c09c26c0e312e30da328167)

Thanks,
Filipe and Popat

**Comment by AparicioJohan** [comment]
Hey @filipematias23 Filipe, 

I understand. Thank you so much, Popat and Filipe! 
Now it is working!

Best
Johan
