### ISSUE TITLE
Another Problem with FieldimageR installation

### ISSUE THREAD

**Issue by Lucasprod2022** [OpenDroneMap/FIELDimageR#62]
I'm trying to install FIELDimageR but i get this error everytime. I would be very gratefull if you could help me with this

devtools::install_github("OpenDroneMap/FIELDimageR")
Downloading GitHub repo OpenDroneMap/FIELDimageR@HEAD
✔  checking for file 'C:\Users\Lucas\AppData\Local\Temp\Rtmp0qy9B0\remotes1d7c43847052\OpenDroneMap-FIELDimageR-72de3eb/DESCRIPTION' ...
─  preparing 'FIELDimageR':
✔  checking DESCRIPTION meta-information ...
   Warning: fieldAUC.Rd:30: unknown macro '\times'
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'FIELDimageR_0.6.1.tar.gz'
   
Installing package into ‘C:/Users/Lucas/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
* installing *source* package 'FIELDimageR' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  **there is no package called 'dplyr'**
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Ejecución interrumpida
ERROR: lazy loading failed for package 'FIELDimageR'
* removing 'C:/Users/Lucas/AppData/Local/R/win-library/4.3/FIELDimageR'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Lucas/AppData/Local/Temp/Rtmp0qy9B0/file1d7c1fa311f3/FIELDimageR_0.6.1.tar.gz’ had non-zero exit status

**Comment by filipematias23** [comment]
Hi Lucas,

Thanks for asking … Normally, R says what is missing. For example, check in your error the part in bold: "**there is no package called 'dplyr'** "

It means that you need to install the package "dplyr".

Hope it helps!
Filipe
