### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Peter-Jackson22** [OpenDroneMap/FIELDimageR#64]
Hello,
I've been trying to install FIELDimageR, everything is up to data and I'm working in R-4.4.0.

This is what I get:
devtools::install_github("OpenDroneMap/FIELDimageR")
Downloading GitHub repo OpenDroneMap/FIELDimageR@HEAD
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\nq928146\AppData\Local\Temp\Rtmpq4gGaa\remotes373828237f72\OpenDroneMap-FIELDimageR-232f163/DESCRIPTION' (8.2s)
─  preparing 'FIELDimageR': (3.1s)
✔  checking DESCRIPTION meta-information (885ms)
   Warning: C:/Users/nq928146/AppData/Local/Temp/RtmpqEGGVp/Rbuild3b246ac365f1/FIELDimageR/man/fieldAUC.Rd:30: unknown macro '\times'
─  checking for LF line-endings in source and make files and shell scripts (2.3s)
─  checking for empty or unneeded directories (1s)
   Omitted 'LazyData' from DESCRIPTION
─  building 'FIELDimageR_0.6.2.tar.gz'
   
* installing *source* package 'FIELDimageR' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'exactextractr'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'FIELDimageR'
* removing 'C:/Users/nq928146/AppData/Local/Programs/R/R-4.4.0/library/FIELDimageR'

it looks like a similar issue to: https://github.com/OpenDroneMap/FIELDimageR/issues/52, but the solution there appears to have been an update to the software from the dev team

**Comment by filipematias23** [comment]
Hey there,

The Error msg says:


*Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck
= vI[[j]]) :there is no package called 'exactextractr'*

That means that you need to install the package *'exactextractr'* before
installing FIELDimageR. Normally, R says what is going wrong in the error !

Try:

install.packages('exactextractr')

devtools::install_github("OpenDroneMap/FIELDimageR")


Hope it helps!

All the best


Em ter., 14 de mai. de 2024 às 12:27, Peter-Jackson22 <
***@***.***> escreveu:

**Comment by Peter-Jackson22** [comment]
All working now. 

Guess I was stupid and missed that
