### ISSUE TITLE
Add a Dockerfile to build docker images

### ISSUE THREAD

**Issue by Chris-Schnaufer** [OpenDroneMap/FIELDimageR#7]
Building Docker images with the base requirements met would allow others to use FIELDimageR with less startup overhead.

I created a `Dockerfile` at https://github.com/Chris-Schnaufer/FIELDimageR/blob/add_dockerfile/Dockerfile that can be merged (if desired) and used to build and distribute a Docker image.

**Comment by dlebauer** [comment]
A few thoughts:

* Use a versioned image?
* rocker provides scripts install2.r and installGithub.r that simplifies installation of R packages. So an alternative for installing the R packages might be:

```
FROM rocker/rstudio:3.6.3
MAINTAINER="Chris Schnaufer <schnaufer@email.arizona.edu>"

RUN apt-get update && apt-get install -y --no-install-recommends \
    libxml2-dev 
    zlib1g-dev 
    libfftw3-dev 
    gdal-bin 
    libgdal-dev 
    libxt-dev

RUN install2.r --error \
    sp
    raster
    rgdal
    scales
    xml2
    git2r
    usethis
    fftwtools
    devtools

RUN installGithub.r filipematias23/FIELDimageR
```

In addition, If you start from rocker/geospatial you get a lot of these dependencies already built in (including tidyverse and a lot of geospatial utilities - not just those required by FieldImageR but some that could be useful for running downstream analyses, as well as a lot of bloat!!)
* it is quite a stack (not clear if additional size / dependencies are worth it), but 
    * rocker/geospatial https://github.com/rocker-org/geospatial/blob/master/Dockerfile builds on
    * rocker/verse https://github.com/rocker-org/rocker-versioned/blob/master/verse/3.6.3.Dockerfile which builds on 
    * rocker/tidyverse https://github.com/rocker-org/rocker-versioned/blob/master/tidyverse/3.6.3.Dockerfile which builds on 
    * rocker/rstudio https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/3.6.3.Dockerfile which builds on 
    * rocker/r-ver which is the base for the versioned images ...

**Comment by filipematias23** [comment]
Thank you for sharing ..!!!

**Comment by Chris-Schnaufer** [comment]
I have updated the Dockerfile to take advantage of suggested installation changes.

I am putting the suggested additions for downstream analysis into another issue

**Comment by Chris-Schnaufer** [comment]
Linking to https://github.com/OpenDroneMap/FIELDimageR/pull/10

**Comment by dlebauer** [comment]
this can be closed since #10 has been merged and suggestions for improvement are in #9

**Comment by filipematias23** [comment]
Hi @Chris-Schnaufer and @dlebauer,
Thank you a lot for helping with this project. 
I am wondering what is the next step? How can I integrate your suggestions (#9 and #10) to the tutorial?

All the best,
Filipe

**Comment by Chris-Schnaufer** [comment]
> I am wondering what is the next step? How can I integrate your suggestions (#9 and #10) to the tutorial?

I think the next step as described in #9 would be to determine if those are changes that are desired and, if so, update the Dockerfile to use the new base image. I don't know who would be best suited to determine if those changes are desired
